/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  // preflight would reset base element styles (headings, buttons) app-wide,
  // which would visibly change the existing plain-CSS chat page at "/".
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#3d0600",
        "on-tertiary-fixed": "#001e2d",
        "on-background": "#271814",
        background: "#fff8f6",
        "surface-variant": "#fadcd5",
        "secondary-fixed-dim": "#ffb4a3",
        "on-tertiary-fixed-variant": "#004c6a",
        "primary-fixed": "#ffdad2",
        "surface-container": "#ffe9e4",
        "surface-tint": "#b52600",
        "surface-dim": "#f1d4cd",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#7fd0ff",
        "inverse-primary": "#ffb4a3",
        "on-secondary-fixed": "#3d0600",
        "inverse-on-surface": "#ffede9",
        "secondary-container": "#f9856a",
        "surface-container-high": "#ffe2db",
        "on-secondary-fixed-variant": "#7f2a16",
        surface: "#fff8f6",
        "error-container": "#ffdad6",
        "outline-variant": "#e4beb5",
        "secondary-fixed": "#ffdad2",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#ffb4a3",
        "surface-container-highest": "#fadcd5",
        "on-secondary-container": "#701e0b",
        "on-error": "#ffffff",
        secondary: "#9f402a",
        "on-primary-fixed-variant": "#8b1b00",
        "on-tertiary": "#ffffff",
        "on-surface": "#271814",
        outline: "#907068",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#c5e7ff",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#fcfcff",
        "tertiary-container": "#007dab",
        "inverse-surface": "#3e2c28",
        "surface-container-low": "#fff0ed",
        "surface-bright": "#fff8f6",
        tertiary: "#006388",
        primary: "#b12500",
        error: "#ba1a1a",
        "on-primary-container": "#fffbff",
        "on-surface-variant": "#5b403a",
        "primary-container": "#d83913",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-lg": ["Noto Sans KR"],
        "headline-md": ["Noto Sans KR"],
        "body-md": ["Noto Sans KR"],
        "headline-sm": ["Noto Sans KR"],
        "label-lg": ["Noto Sans KR"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-lg": [
          "16px",
          { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "700" },
        ],
        "headline-sm": ["24px", { lineHeight: "34px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
